var annotated =
[
    [ "AppDelegate", "interface_app_delegate.html", "interface_app_delegate" ],
    [ "<DewarpPointDelegate>", "protocol_dewarp_point_delegate-p.html", "protocol_dewarp_point_delegate-p" ],
    [ "DewarpPointView", "interface_dewarp_point_view.html", "interface_dewarp_point_view" ],
    [ "ImageEditor", "interface_image_editor.html", "interface_image_editor" ],
    [ "ImageEditor()", "category_image_editor_07_08.html", "category_image_editor_07_08" ],
    [ "<ImageEditorDelegate>", "protocol_image_editor_delegate-p.html", "protocol_image_editor_delegate-p" ],
    [ "ImageEditorView", "interface_image_editor_view.html", "interface_image_editor_view" ],
    [ "ImageEditorView()", "category_image_editor_view_07_08.html", "category_image_editor_view_07_08" ],
    [ "<ImageEditorViewDelegate>", "protocol_image_editor_view_delegate-p.html", "protocol_image_editor_view_delegate-p" ],
    [ "SECMBrightnessAndContrastOperation", "interface_s_e_c_m_brightness_and_contrast_operation.html", "interface_s_e_c_m_brightness_and_contrast_operation" ],
    [ "SECMCaptureDocumentWizardBuilder", "interface_s_e_c_m_capture_document_wizard_builder.html", "interface_s_e_c_m_capture_document_wizard_builder" ],
    [ "<SECMCaptureDocumentWizardDelegate>", "protocol_s_e_c_m_capture_document_wizard_delegate-p.html", "protocol_s_e_c_m_capture_document_wizard_delegate-p" ],
    [ "SECMConvertToBlackAndWhiteOperation", "interface_s_e_c_m_convert_to_black_and_white_operation.html", null ],
    [ "SECMConvertToGrayScaleOperation", "interface_s_e_c_m_convert_to_gray_scale_operation.html", null ],
    [ "SECMDewarpOperation", "interface_s_e_c_m_dewarp_operation.html", "interface_s_e_c_m_dewarp_operation" ],
    [ "SECMDocumentBuilder", "interface_s_e_c_m_document_builder.html", "interface_s_e_c_m_document_builder" ],
    [ "SECMExporter", "interface_s_e_c_m_exporter.html", null ],
    [ "SECMExportOperation", "interface_s_e_c_m_export_operation.html", "interface_s_e_c_m_export_operation" ],
    [ "<SECMExportOperationDelegate>", "protocol_s_e_c_m_export_operation_delegate-p.html", "protocol_s_e_c_m_export_operation_delegate-p" ],
    [ "SECMFixedRotationOperation", "interface_s_e_c_m_fixed_rotation_operation.html", "interface_s_e_c_m_fixed_rotation_operation" ],
    [ "SECMImage", "interface_s_e_c_m_image.html", "interface_s_e_c_m_image" ],
    [ "SECMImageOperation", "interface_s_e_c_m_image_operation.html", "interface_s_e_c_m_image_operation" ],
    [ "<SECMImageOperationDelegate>", "protocol_s_e_c_m_image_operation_delegate-p.html", "protocol_s_e_c_m_image_operation_delegate-p" ],
    [ "SECMLicense", "interface_s_e_c_m_license.html", null ],
    [ "SECMQuadrangle", "interface_s_e_c_m_quadrangle.html", "interface_s_e_c_m_quadrangle" ],
    [ "SECMRotationOperation", "interface_s_e_c_m_rotation_operation.html", "interface_s_e_c_m_rotation_operation" ],
    [ "SimpleScanTests", "interface_simple_scan_tests.html", null ],
    [ "ViewController", "interface_view_controller.html", null ],
    [ "ViewController()", "category_view_controller_07_08.html", "category_view_controller_07_08" ]
];